In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


# Introduction to Tensors
##Creating tensors

In [ ]:
#scalars

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# dimension of the scalar
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([1,2,3])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[1,2],
                        [3,4]])
MATRIX.shape
MATRIX.ndim

2

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR1 = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]],
                        [[11,12,13],
                         [21,22,23],
                         [31,32,33]]])
TENSOR1[0][0]


tensor([1, 2, 3])

#Random numbers

###Why random tensors?
Random tensors are important because the way many neural netweork learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the dataset.

`Start with random numbers -> look at data -> update random numbers`

In [ ]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)

random_tensor


tensor([[0.7745, 0.1343, 0.9265, 0.6297],
        [0.9789, 0.2795, 0.2866, 0.2742],
        [0.4775, 0.5752, 0.6449, 0.3580]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and ones

In [ ]:
#Creating a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creating tensors of all one
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [ ]:
#Use torch.range() and get depreciated message, use torch.arange()
oneToTen = torch.arange(start = 1, end = 10, step = 1)
oneToTen

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input=oneToTen)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
anotherOne = torch.ones_like(input=zero)
anotherOne

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#Tensor datatypes


**Note:** Tensor datatypes is one of the 3 big errors you'll run into with pyTorch and deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
 #Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                                device= None, #what divise is your tensor on
                                requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_tensor_16 = float_32_tensor.type(torch.float16)
float_tensor_16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_tensor_16

tensor([ 9., 36., 81.])

#Getting information from tensors (Tensor attributes)

1. Tensors not right datatype - check `tensor.dtype`
2. Tensors not right shape - check - `tensor.shape`
3. Tensors not on the right device - check device `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4358, 0.6960, 0.8258, 0.0718],
        [0.4001, 0.0220, 0.2620, 0.2451],
        [0.9974, 0.2605, 0.7157, 0.1197]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor operations)

####Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix multiplication (dot product)

There are two main runles that performing matrix multiplication needs to satisfy:

1. The <b>Inner Dimensions</b> must be the same:

`(3,2) @ (3,2)` won't work

`(2,3) @ (3,2)` will work


In [ ]:
#create and tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor1 = tensor * 10
tensor1

tensor([10, 20, 30])

# Matrix multiplication
1. Element-wise multiplication
2. Matrix multiplication (dot product)


In [ ]:
#Element wise multiplication

print(tensor, "*",  tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
print(torch.matmul(tensor, tensor), "this is just the matrix multiplication and addition of all addition")

tensor(14) this is just the matrix multiplication and addition of all addition


In [ ]:
anotherTensor = torch.tensor([1,2,4,5,6,7])

In [ ]:
%%time
sum = 0
for i in range(len(anotherTensor)):
    sum += anotherTensor[i] * anotherTensor[i]
print(sum)


tensor(131)
CPU times: user 1.57 ms, sys: 0 ns, total: 1.57 ms
Wall time: 1.58 ms


In [ ]:
%%time
print(torch.matmul(anotherTensor, anotherTensor))

tensor(131)
CPU times: user 1.37 ms, sys: 0 ns, total: 1.37 ms
Wall time: 2.61 ms


In [ ]:
torch.matmul(anotherTensor, anotherTensor)

tensor(131)

In [ ]:
ten1 = torch.tensor([[1,2,3],
                   [4,5,6]])
ten2 = torch.tensor([[1,2,3],
                   [4,5,6]])
print(ten1)
print(ten2)

print(torch.matmul(ten1, ten2.T))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[14, 32],
        [32, 77]])


In [ ]:
ten1 = torch.tensor([[1,2,3],
                   [4,5,6]], dtype=torch.int32) # Use torch.tensor to create a tensor with specific values
ten2 = torch.tensor([[1,2,3],
                   [4,5,6]], dtype=torch.int32) # Use torch.tensor to create a tensor with specific values
print(ten1)
print(ten2)

print(torch.matmul(ten1, torch.transpose(ten2, 0, 1)))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[14, 32],
        [32, 77]], dtype=torch.int32)


In [ ]:
print(torch.rand(5,2).matmul(torch.rand(2,3)))

tensor([[0.1343, 0.1220, 0.1545],
        [0.8559, 0.7393, 0.9397],
        [1.1176, 0.9694, 1.2317],
        [0.0985, 0.0689, 0.0889],
        [0.8003, 0.7565, 0.9558]])


In [ ]:
tens = torch.tensor([[1,2],
                     [4,5],
                     [7,8]])


print(torch.matmul(tens, tens.T))

tens.T

tensor([[  5,  14,  23],
        [ 14,  41,  68],
        [ 23,  68, 113]])


tensor([[1, 4, 7],
        [2, 5, 8]])

#finding the min, max, mean, (aggregation)
Now we have see a few ways to manupulate tensors, lets run trhough fw ways to aggregate them (got from more valuese to less values)



In [ ]:
#Create a tensor
x = torch.arange(0, 100, 10)
print(x)
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(90)
tensor(45.)
tensor(450)


**Note:** You may find some methods such as torch.mean() requires specific datatype, otherwise the operation will fail

#Positional min/max
You can also find the index of the tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()`


This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [ ]:
 print(x.argmin())
 print(x.argmax())

tensor(0)
tensor(9)



Reshaping, stacking, squeezing and unsqueezing

## Reshaping, Stacking, Squeezing, and Unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them. Below are some popular methods:

| Method                                   | One-line Description                                                                                  |
|------------------------------------------|-----------------------------------------------------------------------------------------------------|
| `torch.reshape(input, shape)`            | Reshapes input to shape (if compatible), can also use `torch.Tensor.reshape()`.                    |
| `Tensor.view(shape)`                     | Returns a view of the original tensor in a different shape but shares the same data as the original tensor. |
| `torch.stack(tensors, dim=0)`           | Concatenates a sequence of tensors along a new dimension (`dim`), all tensors must be the same size. |
| `torch.squeeze(input)`                   | Squeezes input to remove all the dimensions with value 1.                                          |
| `torch.unsqueeze(input, dim)`            | Returns input with a dimension value of 1 added at `dim`.                                          |
| `torch.permute(input, dims)`             | Returns a view of the original input with its dimensions permuted (rearranged) to `dims`.         |


In [ ]:
y = torch.arange(1, 10)
y, y.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
reshapedY = torch.reshape(y, (1,9))
reshapedY

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#change the view
z = y.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes y (Because a view of a tensor shares the same as te original)
# z[:] = 5
z, y

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#stack tensors on top of each other
lol = torch.rand(3,3,3)
lol_stacked = torch.stack((lol, lol), dim=1)
lol, lol_stacked

(tensor([[[0.3649, 0.6337, 0.2041],
          [0.6480, 0.4312, 0.8773],
          [0.8124, 0.6293, 0.8486]],
 
         [[0.5058, 0.5448, 0.3457],
          [0.3627, 0.1656, 0.6053],
          [0.5177, 0.3495, 0.1030]],
 
         [[0.5166, 0.9946, 0.6726],
          [0.6777, 0.4705, 0.7422],
          [0.6330, 0.2772, 0.0389]]]),
 tensor([[[[0.3649, 0.6337, 0.2041],
           [0.6480, 0.4312, 0.8773],
           [0.8124, 0.6293, 0.8486]],
 
          [[0.3649, 0.6337, 0.2041],
           [0.6480, 0.4312, 0.8773],
           [0.8124, 0.6293, 0.8486]]],
 
 
         [[[0.5058, 0.5448, 0.3457],
           [0.3627, 0.1656, 0.6053],
           [0.5177, 0.3495, 0.1030]],
 
          [[0.5058, 0.5448, 0.3457],
           [0.3627, 0.1656, 0.6053],
           [0.5177, 0.3495, 0.1030]]],
 
 
         [[[0.5166, 0.9946, 0.6726],
           [0.6777, 0.4705, 0.7422],
           [0.6330, 0.2772, 0.0389]],
 
          [[0.5166, 0.9946, 0.6726],
           [0.6777, 0.4705, 0.7422],
           [0.633

tensor([[0.2227, 0.6152, 0.6035],
        [0.3936, 0.8901, 0.0410]], dtype=torch.float16)

#Squeez and unsqueez

In [ ]:
a = torch.rand(2,3,1,2)
a

tensor([[[[0.6867, 0.8734]],

         [[0.6183, 0.9653]],

         [[0.7216, 0.1852]]],


        [[[0.7754, 0.6786]],

         [[0.7491, 0.4121]],

         [[0.1435, 0.7404]]]])

**Squeeze** removes all the single dimensions from a target tensor

In [ ]:
a_squeezed = a.squeeze?
a_squeezed.shape, a.shape

(torch.Size([2, 3, 2]), torch.Size([2, 3, 1, 2]))

**Unsqueeze** `torch.unsqueeze` - adds a single dimension to a target tensor at a specific dim (dimension)

In [ ]:
print(f"Previous tensor: {a_squeezed}")
print(f"Previous shape: {a_squeezed.shape}")


#adding an extra dimenstion with unsqueeze
print("---------------------------------")
a_unsqueezed = a_squeezed.unsqueeze(dim=2)
print(f"\nNew tensor: {a_unsqueezed}")
print(f"New shape: {a_unsqueezed.shape}")

Previous tensor: tensor([[[0.6867, 0.8734],
         [0.6183, 0.9653],
         [0.7216, 0.1852]],

        [[0.7754, 0.6786],
         [0.7491, 0.4121],
         [0.1435, 0.7404]]])
Previous shape: torch.Size([2, 3, 2])
---------------------------------

New tensor: tensor([[[[0.6867, 0.8734]],

         [[0.6183, 0.9653]],

         [[0.7216, 0.1852]]],


        [[[0.7754, 0.6786]],

         [[0.7491, 0.4121]],

         [[0.1435, 0.7404]]]])
New shape: torch.Size([2, 3, 1, 2])


**permute**

torch.permute(input, dims) → Tensor
Returns a view of the original tensor input with its dimensions permuted.

Parameters
input (Tensor) – the input tensor.

dims (tuple of int) – The desired ordering of dimensions

`torch.permute` - rearranges the dimensions of a target tensor in a specified order


In [ ]:
x_original = torch.rand(224, 224, 3) # this is height, width nad colour_channels
x_permuted = x_original.permute(2, 0 , 1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 3
x_original[0,0,0]

tensor(3.)